import os
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

router = APIRouter(
    prefix="/monitoring",
    tags=["monitoring"]
)

REPORT_PATH = "/app/reports/toxicity_drift_report.html"

@router.get("/drift_report", response_class=FileResponse)
async def get_drift_report():
    """
    Returns the latest Evidently AI drift report generated by Airflow.
    """
    if not os.path.exists(REPORT_PATH):
        raise HTTPException(status_code=404, detail="Drift report not found. Has the Airflow DAG completed?")
    
    return FileResponse(REPORT_PATH, media_type="text/html")
